~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_10.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_500000_100.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/graph_5000000_10.out" 12 >> ~/thesis_page_rank/result.txt

~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 1 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 2 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 4 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 8 >> ~/thesis_page_rank/result.txt
~/spark-3.1.2-bin-hadoop3.2/bin/spark-submit --master spark://wca-rpi4-7:7077 /home/wcauser3/thesis_page_rank/sparkX/pageRank.py "/home/wcauser3/thesis_page_rank/cpp/page_rank_with_redis/data/soc-LiveJournal1.out" 12 >> ~/thesis_page_rank/result.txt